(()=>{'use strict';
const C=window.EquateCore,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SAVE='equate-intentional-save-v9',BEST='equate-best-v9',SEEN='equate-tutorial-seen-v2',LABEL={add:'Addition',sub:'Subtraction',mul:'Multiplication',div:'Division',mixed:'Mixed'};
const state={mode:'solo',op:null,difficulty:null,stage:1,rows:5,cols:5,board:[],selected:[],hintCells:[],found:0,stageScore:0,hintPenalty:0,hintsUsed:0,history:[],secondsLeft:600,timerId:null,paused:false,sound:true,stageActive:false,inputEnabled:true,pointerDown:false,runningScore:0,quickBonus:0,lastSolveAt:null,players:['Player 1','Player 2'],playerScores:[0,0],turn:0};
function show(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));}
function args(cells){return {board:state.board,rows:state.rows,cols:state.cols,cells,stage:state.stage,mode:state.op};}
function move(cells){return C.validateMove(args(cells));}
function clearTransient(){state.pointerDown=false;state.selected=[];state.hintCells=[];state.inputEnabled=true;}
function startStage(){
 clearInterval(state.timerId);clearTransient();Object.assign(state,{found:0,stageScore:0,hintPenalty:0,hintsUsed:0,history:[],secondsLeft:600,paused:false,stageActive:true,quickBonus:0,lastSolveAt:performance.now()});
 $('#stageOverlay').hidden=true;$('#pauseOverlay').hidden=true;$('#unlockOverlay').hidden=true;show('game');newBoard();renderAll();startTimer();maybeUnlockDemo();
}
function newBoard(){clearTransient();state.inputEnabled=false;const made=C.generateBoard({difficulty:state.difficulty,stage:state.stage,mode:state.op});state.board=made.board;state.rows=made.rows;state.cols=made.cols;renderBoard();state.inputEnabled=true;}
function renderBoard(){const b=$('#board');b.innerHTML='';b.style.setProperty('--cols',state.cols);state.board.forEach((cell,i)=>{const el=document.createElement('button');el.className='cell'+(cell.blank?' blank':'');el.dataset.i=i;el.textContent=cell.blank?'':cell.value;el.setAttribute('aria-label',cell.blank?'cleared':String(cell.value));b.appendChild(el);});fitBoard();syncClasses();}
function syncClasses(){$$('#board .cell').forEach((el,i)=>{el.classList.toggle('selected',state.selected.includes(i));el.classList.toggle('hint',state.hintCells.includes(i));});}
function fitBoard(){const w=$('#boardWrap');if(!w)return;const cell=Math.max(27,Math.min(92,Math.floor(Math.min((w.clientWidth-14)/state.cols,(w.clientHeight-14)/state.rows))));$('#board').style.setProperty('--cell',cell+'px');}
function canAppend(i){if(!state.inputEnabled||state.board[i].blank||state.selected.includes(i))return false;if(!state.selected.length)return true;const partial=[...state.selected,i];if(partial.length===3)return !!move(partial)||pathOnly(partial);return pathOnly(partial);}
function pathOnly(cells){if(cells.length===2){const fake=[...cells,cells[1]];const d=C.validatePath(state.board,state.rows,state.cols,[cells[0],cells[1],nextCandidate(cells[1],cells[0])],state.stage);return !!d||rayAllowed(cells[0],cells[1]);}return !!C.validatePath(state.board,state.rows,state.cols,cells,state.stage);}
function rayAllowed(a,b){const d=C.validatePath;const [r1,c1]=[Math.floor(a/state.cols),a%state.cols],[r2,c2]=[Math.floor(b/state.cols),b%state.cols],rd=Math.sign(r2-r1),cd=Math.sign(c2-c1);if(!((r1===r2)||(c1===c2)||(Math.abs(r2-r1)===Math.abs(c2-c1))))return false;const name=Object.entries(C.DIRS).find(([,v])=>v[0]===rd&&v[1]===cd)?.[0];if(!C.allowedDirections(state.stage).includes(name))return false;let r=r1+rd,c=c1+cd;while(r!==r2||c!==c2){if(!state.board[r*state.cols+c].blank)return false;r+=rd;c+=cd;}return true;}
function nextCandidate(){return -1;}
function selectTile(i){if(!state.stageActive||state.paused||!state.inputEnabled)return;if(state.selected.includes(i)){clearSelection();return;}if(!canAppend(i)){bad('That path is blocked or not unlocked.');return;}state.selected.push(i);state.hintCells=[];syncClasses();if(state.selected.length===3){const eq=move(state.selected);if(eq)solve(eq);else bad('Not an equation — try again.');}}
function clearSelection(delay=0){setTimeout(()=>{state.selected=[];state.hintCells=[];syncClasses();},delay);}
function bad(msg){feedback(msg,'bad');beep(120,.08);$$('#board .selected').forEach(x=>x.classList.add('rejected'));clearSelection(260);if(state.mode==='two')switchTurn();}
function solve(eq){state.inputEnabled=false;state.history.push({cells:eq.cells.map(i=>({i,value:state.board[i].value})),found:state.found,stageScore:state.stageScore,turn:state.turn,playerScores:[...state.playerScores]});eq.cells.forEach(i=>state.board[i].blank=true);state.found++;state.stageScore=Math.min(100,state.stageScore+10);const bonus=quickBonus();state.quickBonus+=bonus;if(state.mode==='two')state.playerScores[state.turn]+=10+bonus;showEquation(eq.text);if(bonus)showBonus(bonus);beep(620,.09);clearTransient();renderAll();if(state.found>=10){finish();return;}if(state.mode==='two')switchTurn();setTimeout(()=>{if(!C.enumerate(args([]),1).length)newBoard();else state.inputEnabled=true;},260);}
function quickBonus(){const now=performance.now(),s=(now-state.lastSolveAt)/1000;state.lastSolveAt=now;return s<=3?8:s<=5?5:s<=8?3:0;}
function switchTurn(){if(state.mode!=='two')return;state.turn=1-state.turn;renderPlayers();}
function hint(){if(!state.stageActive||state.paused)return;const hit=C.enumerate(args([]),1)[0];if(!hit){newBoard();return;}if(state.hintsUsed>=2){const charge=Math.min(5,state.mode==='two'?state.playerScores[state.turn]:Math.max(0,state.stageScore-state.hintPenalty));state.hintPenalty+=charge;if(state.mode==='two')state.playerScores[state.turn]-=charge;}state.hintsUsed++;state.selected=[];state.hintCells=hit.cells;syncClasses();feedback(`Hint: ${hit.text}`,'warn');beep(440,.08);renderAll();}
function undo(){if(!state.stageActive||state.paused)return;const s=state.history.pop();if(!s){feedback('Nothing to undo.','warn');return;}s.cells.forEach(c=>{state.board[c.i].value=c.value;state.board[c.i].blank=false;});state.found=s.found;state.stageScore=s.stageScore;state.turn=s.turn;state.playerScores=s.playerScores;clearTransient();renderAll();}
function hintText(){return state.hintsUsed===0?'2 FREE':state.hintsUsed===1?'1 FREE':'−5 POINTS';}
function renderAll(){$('#stageLabel').textContent=state.stage;$('#modeLabel').textContent=`${LABEL[state.op]} · ${state.difficulty[0].toUpperCase()+state.difficulty.slice(1)}`;$('#runningScoreLabel').textContent=state.mode==='two'?state.playerScores[state.turn]:state.runningScore+Math.max(0,state.stageScore-state.hintPenalty)+state.quickBonus;$('#bestLabel').textContent=localStorage.getItem(BEST)||0;$('#foundLabel').textContent=state.found;$('#scoreLabel').textContent=Math.max(0,state.stageScore-state.hintPenalty);$('#progressFill').style.width=state.found*10+'%';$('#hintCost').textContent=hintText();$('#rulesIndicator').textContent=C.rulesText(state.stage);$('#turnPanel').hidden=state.mode!=='two';$('#scoreTitle').textContent=state.mode==='two'?'TURN SCORE':'SCORE';renderPlayers();renderTimer();renderBoard();}
function renderPlayers(){$('#turnLabel').textContent=state.mode==='two'?`${state.players[state.turn]}'s turn`:'';$('#p1Score').textContent=`${state.players[0]} ${state.playerScores[0]}`;$('#p2Score').textContent=`${state.players[1]} ${state.playerScores[1]}`;}
function renderTimer(){const s=state.secondsLeft;$('#timerLabel').textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;const deg=s/600*360;$('#timerRing').style.background=`conic-gradient(#5df02e 0 ${deg*.55}deg,#ffc400 ${deg*.55}deg ${deg*.8}deg,#ff4d55 ${deg*.8}deg ${deg}deg,#201825 ${deg}deg)`;}
function startTimer(){clearInterval(state.timerId);state.timerId=setInterval(()=>{if(!state.paused&&state.stageActive){state.secondsLeft--;renderTimer();if(state.secondsLeft<=0)finish();}},1000);}
function finish(){clearInterval(state.timerId);state.stageActive=false;const points=Math.max(0,state.stageScore-state.hintPenalty)+state.quickBonus;if(state.mode==='solo'){state.runningScore+=points;const best=Math.max(Number(localStorage.getItem(BEST)||0),state.runningScore);localStorage.setItem(BEST,best);}$('#resultBase').textContent=Math.max(0,state.stageScore-state.hintPenalty);$('#resultBonus').textContent='+'+state.quickBonus;$('#resultPenalty').textContent='−'+state.hintPenalty;$('#resultTotal').textContent=state.mode==='two'?state.playerScores.join(' — '):points;$('#winnerLine').textContent=state.mode==='two'?(state.playerScores[0]===state.playerScores[1]?'Tie game!':`${state.players[state.playerScores[0]>state.playerScores[1]?0:1]} leads!`):'';$('#stageOverlay').hidden=false;clearIntentionalSave();}
function pause(){if(!state.stageActive)return;state.paused=true;state.pointerDown=false;$('#pauseOverlay').hidden=false;}
function resumePause(){state.paused=false;state.inputEnabled=true;$('#pauseOverlay').hidden=true;}
function intentionalSave(){const data={...state,timerId:null,pointerDown:false,selected:[],hintCells:[],history:[]};localStorage.setItem(SAVE,JSON.stringify(data));$('#resumeBtn').hidden=false;}
function clearIntentionalSave(){localStorage.removeItem(SAVE);$('#resumeBtn').hidden=true;}
function restore(){const raw=localStorage.getItem(SAVE);if(!raw)return;Object.assign(state,JSON.parse(raw));clearTransient();state.stageActive=true;state.paused=false;show('game');renderAll();startTimer();}
function feedback(t,kind=''){$('#equationToast').textContent=t;$('#equationToast').className='equation-toast '+kind;clearTimeout(feedback.t);feedback.t=setTimeout(()=>$('#equationToast').textContent='',1500);}
function showEquation(t){feedback(t+' ✓','good');}
function showBonus(n){const e=$('#bonusToast');e.textContent=(n===8?'⚡ LIGHTNING':n===5?'⚡ QUICK':'FAST')+` +${n}`;e.classList.add('bonus-pop');setTimeout(()=>{e.textContent='';e.classList.remove('bonus-pop');},900);}
function beep(freq,dur){if(!state.sound)return;try{const a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.value=.035;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+dur);o.stop(a.currentTime+dur);}catch{}}
function toggleFullscreen(){document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();}

const tutorialBase=[4,3,7,9,5, 11,6,12,8,4, 5,10,15,7,14, 3,6,9,2,8, 8,4,12,16,20].map((value,id)=>({id,value,blank:false}));let tutorialTimers=[];
const demos=[{cells:[0,1,2],text:'4 + 3 = 7',label:'Across: three touching tiles.'},{cells:[4,9,14],values:[5,4,9],text:'5 + 4 = 9',label:'Up or down: three touching tiles.'}];
function validateTutorialMove(board,cells,stage=1,mode='add'){const result=C.validateMove({board,rows:5,cols:5,cells,stage,mode});if(!result)throw new Error('Tutorial move failed shared validator');return result;}
function buildTutorial(board=tutorialBase){const b=$('#tutorialBoard');b.innerHTML='';board.forEach((x,i)=>{const d=document.createElement('div');d.className='tcell'+(x.blank?' cleared':'');d.dataset.i=i;d.textContent=x.blank?'':x.value;b.appendChild(d);});}
function mark(cells,cls,on=true){cells.forEach(i=>$(`#tutorialBoard .tcell[data-i="${i}"]`)?.classList.toggle(cls,on));}
function runTutorial(){tutorialTimers.forEach(clearTimeout);tutorialTimers=[];const board=tutorialBase.map(x=>({...x}));validateTutorialMove(board,[0,1,2]);const vertical=board.map(x=>({...x}));[5,4,9].forEach((v,k)=>vertical[[4,9,14][k]].value=v);validateTutorialMove(vertical,[4,9,14]);buildTutorial(board);$('#tutorialReady').hidden=true;let at=500;const schedule=(fn,t)=>tutorialTimers.push(setTimeout(fn,t));
 demos.forEach((d,n)=>{schedule(()=>{if(d.values)d.cells.forEach((i,k)=>{board[i].value=d.values[k];$(`#tutorialBoard .tcell[data-i="${i}"]`).textContent=d.values[k];});$('#tutorialStep').textContent=d.label;$('#tutorialRule').textContent='Numbers light up one at a time.';mark(d.cells,'demo');},at);d.cells.forEach((cell,k)=>schedule(()=>mark([cell],'pulse'),at+700+k*600));schedule(()=>$('#tutorialEquation').textContent=d.text+' ✓',at+2700);schedule(()=>{d.cells.forEach(i=>board[i].blank=true);buildTutorial(board);$('#tutorialEquation').textContent='';},at+3900);at+=4700;});
 schedule(()=>{board[20].value=8;board[22].value=4;board[24].value=12;board[21].blank=board[23].blank=true;validateTutorialMove(board,[20,22,24]);buildTutorial(board);$('#tutorialStep').textContent='Cleared white spaces are okay.';$('#tutorialRule').textContent='8 → 4 → 12 is legal because only cleared spaces are between them.';mark([20,22,24],'demo');},at);schedule(()=>$('#tutorialEquation').textContent='8 + 4 = 12 ✓',at+2800);schedule(()=>{board[6].value=2;board[7].value=99;board[8].value=7;if(C.validateMove({board,rows:5,cols:5,cells:[6,8,9],stage:9,mode:'add'}))throw new Error('Tutorial illegal move was accepted');buildTutorial(board);mark([6,8],'illegal');$('#tutorialStep').textContent='Never skip an active number.';$('#tutorialEquation').textContent='2 → 7  ✕';$('#tutorialRule').textContent='The uncleared 99 blocks the path.';},at+4700);schedule(()=>{$('#tutorialReady').hidden=false;$('#tutorialStep').textContent='That’s it!';$('#tutorialEquation').textContent='';$('#tutorialRule').textContent='Find equations. Clear tiles. Score points.';},at+7800);}
let tutorialDestination='home';
function openTutorial(destination='home'){tutorialDestination=destination;show('tutorial');runTutorial();}
function tutorialDone(){tutorialTimers.forEach(clearTimeout);localStorage.setItem(SEEN,'1');show(tutorialDestination);}
function maybeUnlockDemo(){if(state.stage!==3&&state.stage!==5)return;state.paused=true;const diagonal=state.stage===3,demo=Array.from({length:25},(_,id)=>({id,value:0,blank:false}));let cells,mode;if(diagonal){demo[0].value=4;demo[6].value=3;demo[12].value=7;cells=[0,6,12];mode='add';}else{demo[0].value=7;demo[1].value=3;demo[2].value=10;cells=[2,1,0];mode='sub';}if(!C.validateMove({board:demo,rows:5,cols:5,cells,stage:state.stage,mode}))throw new Error('Unlock demo failed shared validator');$('#unlockTitle').textContent=diagonal?'DIAGONAL UNLOCKED!':'REVERSE UNLOCKED!';$('#unlockCopy').textContent=diagonal?'Equations can now run corner to corner.':'The same equation may now be traced in the opposite direction.';$('#unlockBoard').textContent=diagonal?'4  ↘  3  ↘  7':'10  ←  3  ←  7';$('#unlockOverlay').hidden=false;}

$('#board').addEventListener('pointerdown',e=>{const x=e.target.closest('.cell');if(!x||x.classList.contains('blank'))return;e.preventDefault();state.pointerDown=true;selectTile(Number(x.dataset.i));});$('#board').addEventListener('pointermove',e=>{if(!state.pointerDown)return;const x=document.elementFromPoint(e.clientX,e.clientY)?.closest('.cell');if(x&&!x.classList.contains('blank')){const i=Number(x.dataset.i);if(state.selected.at(-1)!==i)selectTile(i);}});window.addEventListener('pointerup',()=>state.pointerDown=false);window.addEventListener('pointercancel',()=>state.pointerDown=false);window.addEventListener('blur',()=>state.pointerDown=false);
function chooseMode(mode){state.mode=mode;$('#setupTitle').textContent=mode==='two'?'2 Player Head-to-Head':'Solo Game';$('#playerNames').hidden=mode!=='two';show('setup');}
$('#soloBtn').onclick=()=>{chooseMode('solo');if(!localStorage.getItem(SEEN))openTutorial('setup');};$('#twoBtn').onclick=()=>chooseMode('two');$$('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));$('#operationChoices').onclick=e=>{const b=e.target.closest('[data-op]');if(!b)return;state.op=b.dataset.op;$$('#operationChoices .choice').forEach(x=>x.classList.toggle('selected',x===b));$('#playBtn').disabled=!(state.op&&state.difficulty);};$('#difficultyChoices').onclick=e=>{const b=e.target.closest('[data-diff]');if(!b)return;state.difficulty=b.dataset.diff;$$('#difficultyChoices .choice').forEach(x=>x.classList.toggle('selected',x===b));$('#playBtn').disabled=!(state.op&&state.difficulty);};
$('#playBtn').onclick=()=>{state.stage=1;state.runningScore=0;state.playerScores=[0,0];state.turn=0;state.players=[$('#p1Name').value.trim()||'Player 1',$('#p2Name').value.trim()||'Player 2'];clearIntentionalSave();startStage();};$('#hintBtn').onclick=hint;$('#undoBtn').onclick=undo;$('#pauseBtn').onclick=pause;$('#resumeGameBtn').onclick=resumePause;$('#quitSaveBtn').onclick=()=>{state.paused=true;$('#quitSaveOverlay').hidden=false;};$('#cancelQuitBtn').onclick=()=>{state.paused=false;$('#quitSaveOverlay').hidden=true;};$('#saveQuitBtn').onclick=()=>{intentionalSave();clearInterval(state.timerId);state.stageActive=false;state.paused=false;$('#quitSaveOverlay').hidden=true;show('home');};$('#quitNoSaveBtn').onclick=()=>{clearIntentionalSave();clearInterval(state.timerId);state.stageActive=false;state.paused=false;$('#quitSaveOverlay').hidden=true;show('home');};$('#replayBtn').onclick=startStage;$('#nextBtn').onclick=()=>{state.stage++;startStage();};$('#fullscreenBtn').onclick=toggleFullscreen;$('#soundBtn').onclick=()=>{state.sound=!state.sound;$('#soundBtn .control-icon').textContent=state.sound?'🔊':'🔇';};$('#resumeBtn').onclick=restore;$('#howToBtn').onclick=()=>openTutorial('home');$('#skipTutorialBtn').onclick=tutorialDone;$('#tutorialPlayBtn').onclick=tutorialDone;$('#replayTutorialBtn').onclick=runTutorial;$('#unlockContinue').onclick=()=>{state.paused=false;$('#unlockOverlay').hidden=true;};window.addEventListener('resize',()=>requestAnimationFrame(fitBoard));document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.stageActive&&!state.paused)pause();});$('#resumeBtn').hidden=!localStorage.getItem(SAVE);
})();
